// Visual step-by-step demo tutorial for SQL Account support onboarding.
// Screenshots extracted directly from the official SQL Account KB PDFs
// (cdn.sql.com.my) used to build js/tutorials.js. Each lesson here is a
// tight 2-5 step visual sequence covering the key dialogs/menus a support
// agent needs to recognize, instead of the full PDF walkthrough — target
// is ~20 minutes of learning per day.

export const DEMO_STEPS = {
  1: {
    topic: "Orientation & Setup",
    goal: "The new hire understands what SQL Account is and can get a fresh install running end to end.",
    lessons: [
      {
        title: "How to Install SQL Account",
        steps: [
          { image: "assets/tutorials/day1/how-to-install-sql-account/step1.jpg", caption: "Accept the License Agreement in the installer and click Next to continue.", explanation: "The title bar shows the exact build being installed (e.g. 5.2023.963.835) — always note this version number, because a customer's symptom can be a known bug fixed in a later build. The EULA is issued by eStream Software Sdn Bhd; customers occasionally ask what they're agreeing to, and it's simply the standard end-user license for the SQL software product, not a support contract." },
          { image: "assets/tutorials/day1/how-to-install-sql-account/step2.jpg", caption: "Choose additional setup tasks (desktop icon, Quick Launch icon) and continue the install.", explanation: "Only \"Create a desktop icon\" is ticked by default, which is why some users report \"I can't find SQL Account after installing\" — the icon exists but only on the desktop unless Quick Launch was also ticked. This is a harmless, easily-missed step, but worth mentioning proactively when walking a customer through a fresh install over the phone." },
          { image: "assets/tutorials/day1/how-to-install-sql-account/step3.jpg", caption: "After install, open File > Logon from the main menu to log in to a company.", explanation: "Logon is how you switch between company databases without closing and reopening the whole application — a very common support instruction (\"just do File > Logon and pick the other company\"). Note the other options in the same menu, especially Backup Database and 2-Step Verification, which are frequent destinations for later tickets." },
          { image: "assets/tutorials/day1/how-to-install-sql-account/step4.jpg", caption: "Use Create New Database (or Create Sample Database) under Management to spin up a fresh demo company.", explanation: "Create New Database gives an empty chart of accounts the customer must set up from scratch, while Create Sample Database preloads demo transactions — useful for training or testing report behavior without real data. Also note Restore sits right above these; customers sometimes click Restore by mistake when they actually meant to create a brand-new company." },
          { image: "assets/tutorials/day1/how-to-install-sql-account/step5.jpg", caption: "Log on with the default credentials — username ADMIN, password ADMIN — to enter the new company.", explanation: "ADMIN/ADMIN is the well-known default on every fresh install, so this is also the first thing a support agent should tell a customer to change once they're in — leaving it unchanged is a real security risk, especially on networked installs. If a customer says they \"can't log in\" right after install, this default is the first thing to try before assuming a corrupted database." },
        ],
      },
      {
        title: "Account Book Registration in SQL",
        steps: [
          { image: "assets/tutorials/day1/account-book-registration-in-sql/step1.jpg", caption: "Go to File > Company Profile to start registration.", explanation: "Company Profile is the single source of truth for the company's legal name and address used throughout the system — on invoices, statements, and crucially on the activation request. Agents should always check this screen first when a customer says their invoices show the wrong company details." },
          { image: "assets/tutorials/day1/account-book-registration-in-sql/step2.jpg", caption: "Fill in the company's exact name and address, then click the diskette icon to save — punctuation must match exactly since activation is issued against these details.", explanation: "The disk/save icon at top-left is easy to miss since the form otherwise looks like a normal data-entry screen. A frequent activation failure comes from a comma, \"Sdn Bhd\" vs \"SDN. BHD.\", or a typo here not matching what SQL's licensing server has on file — always double-check this screen character-for-character before troubleshooting an activation code rejection." },
          { image: "assets/tutorials/day1/account-book-registration-in-sql/step3.jpg", caption: "Go to File > Product Activation to open the activation request screen.", explanation: "This is the same File menu customers already used for Company Profile and Logon, so it's worth teaching them to recognize this menu as \"where all the licensing actions live.\" Product Activation is greyed out or behaves oddly if Company Profile hasn't been saved first, which is a common reason customers get stuck at this step." },
          { image: "assets/tutorials/day1/account-book-registration-in-sql/step4.jpg", caption: "Click Print Activation Request, then export it to PDF to email to the local sales agent.", explanation: "The export dropdown offers a dozen formats (Excel, HTML, RTF, DBF, etc.) and it's easy for a customer to pick the wrong one — always confirm they land on \"Export to PDF file\" since that's the format the sales/support team expects to receive. This document carries the company's Digit A code (visible top-right on the request), which the customer should never alter or retype." },
          { image: "assets/tutorials/day1/account-book-registration-in-sql/step5.jpg", caption: "When the code arrives, key it in and confirm Digit A and Digit B match exactly before clicking Register.", explanation: "Digit A and Digit B are checksum-style values generated from the company profile and the returned activation code respectively — if either doesn't match what's printed on the vendor's reply, the registration will fail even if the Activation Code itself looks correctly typed. This mismatch is one of the most common \"activation won't work\" tickets, and the fix is almost always re-checking Company Profile spelling rather than the code itself." },
        ],
      },
      {
        title: "How to Register Your New Company and Change Company Address",
        steps: [
          { image: "assets/tutorials/day1/how-to-register-your-new-company-and-change-company-address/step1.jpg", caption: "Open File > Product Activation to begin (or re-run) the registration/activation request.", explanation: "This is the exact same screen used for first-time registration, which is the whole point of this lesson: a company that has moved premises re-runs this flow rather than needing a new install or new database. Agents should reassure customers that re-registering does not wipe their transaction data." },
          { image: "assets/tutorials/day1/how-to-register-your-new-company-and-change-company-address/step2.jpg", caption: "Confirm the company name and address shown, note Digit A, then click Print Activation Request — the same flow is repeated with the new address when a company has moved and needs re-registration.", explanation: "The Digit A shown here (7648 in this example) will change once the Company Profile address is updated, since it's derived from those exact details — so if a customer changed their address in Company Profile but forgot to save, this screen will still show the old Digit A and the new activation request will be rejected. Always confirm the address on this screen matches the customer's current premises before printing the request." },
        ],
      },
      {
        title: "How To Activate License",
        steps: [
          { image: "assets/tutorials/day1/how-to-activate-license/step1.jpg", caption: "Under the Tools menu, open Logon while logged in as ADMIN to begin activation.", explanation: "The screenshot shows the File menu with Product Activation highlighted — this is the practical starting point agents should point customers to, since Product Activation and Company Profile live together under File on every version of SQL Account. If a customer can't find this menu item, it usually means they're not logged in as a user with sufficient rights (ADMIN or equivalent)." },
          { image: "assets/tutorials/day1/how-to-activate-license/step2.jpg", caption: "In the Company Profile screen, paste the Company Name and Address exactly as shown in the vendor's license PDF — don't retype them.", explanation: "This is the vendor's Activation Code Reply Form side-by-side with the Product Activation dialog — Product ID, Digit A, the long Activation Code, and Digit B must all be copied character-for-character from the PDF into the matching fields. Manually retyping long codes like \"MS6D-CH7W-...-UP6V-SZ8K\" is the single biggest source of activation errors, so always tell customers to copy-paste from the PDF rather than type it out." },
          { image: "assets/tutorials/day1/how-to-activate-license/step3.jpg", caption: "Open File > Product Activation from the menu.", explanation: "Note the window title now shows the actual company name (E STREAM MSC SDN BHD) instead of <<New Company>>, confirming Company Profile was already saved before reaching this step — activation will fail silently or reject the code if that save didn't happen first." },
          { image: "assets/tutorials/day1/how-to-activate-license/step4.jpg", caption: "In the Export menu of the activation screen, choose Export to PDF file to generate the activation request document.", explanation: "This screen actually shows the completed Product Activation dialog with Digit A (4890) and Digit B (1079) matching the vendor's reply form, and the Register button highlighted — the practical lesson is that once both digit pairs agree, Register is a one-click action. If Digit A doesn't match here, stop and go back to Company Profile rather than pressing Register." },
          { image: "assets/tutorials/day1/how-to-activate-license/step5.jpg", caption: "Paste the Product ID and Activation Code from the vendor, confirm Digit A/Digit B match, then click Register.", explanation: "This step revisits File > Company Profile after registration to double check the Company Name field (highlighted yellow) — a good habit for support agents is to always re-open Company Profile after a successful activation to confirm the saved name is exactly what appears on the customer's official documents, since anything typed here flows onto every printed invoice and statement." },
        ],
      },
      {
        title: "Network Setting",
        steps: [
          { image: "assets/tutorials/day1/network-setting/step1.jpg", caption: "Download and install Firebird Server matching the OS bitness (32-bit or 64-bit) on the server PC.", explanation: "Picking the wrong architecture (x86 vs x64) is a classic cause of \"SQL Account won't connect to the server\" tickets — always ask the customer to check whether their server OS is 32-bit or 64-bit in Windows System settings before sending them a download link. Firebird 3.0.1 shown here is one of several supported versions; mismatched Firebird versions between server and client can also cause connection failures." },
          { image: "assets/tutorials/day1/network-setting/step2.jpg", caption: "During Firebird setup, choose SuperServer mode and run it as a Service so it starts automatically.", explanation: "Running Firebird as a Service (rather than an Application) means the database engine starts automatically on server boot without anyone needing to log in — if a customer reports SQL Account can't connect after a server restart, check whether Firebird was installed as an Application instead, which requires someone to manually launch it each time." },
          { image: "assets/tutorials/day1/network-setting/step3.jpg", caption: "Set a SYSDBA password for the Firebird database system administrator during install.", explanation: "This SYSDBA password protects the Firebird engine itself, separate from any SQL Account user password — customers often confuse the two, and losing/forgetting the SYSDBA password later can complicate database recovery tasks done via command-line tools. Note the warning that Firebird 3's default password differs from earlier versions (masterkey vs masterke)." },
          { image: "assets/tutorials/day1/network-setting/step4.jpg", caption: "On each client PC, use Add Group and browse the network to the server's shared Default.DCF file to connect.", explanation: "The client must browse across the actual Windows network share (as shown, \\\\CHRISVOSTRO\\Share\\) to find Default.DCF — if the client PC can't see the server in this file browser, the problem is almost always Windows network/sharing permissions rather than anything inside SQL Account itself, so check that first." },
          { image: "assets/tutorials/day1/network-setting/step5.jpg", caption: "Once connected, the SQL Financial Accounting Database Group screen lists the shared company database — this confirms the client can see the server." , explanation: "Seeing the company database listed here confirms the client machine can reach the server share and the Firebird service is running and reachable — if this screen stays empty, the problem is in the network/Firebird setup from earlier steps, not in SQL Account itself, so don't waste time troubleshooting inside the accounting application at this point." },
        ],
      },
      {
        title: "Enlarging UI Screen in SQL",
        steps: [
          { image: "assets/tutorials/day1/enlarging-ui-screen-in-sql/step1.jpg", caption: "Right-click the desktop and choose Display settings — this is a Windows setting, not an in-app option.", explanation: "This is worth stating clearly to customers who ask \"how do I make SQL Account's font bigger\" — there is no in-app zoom control, so the fix always happens in Windows display settings, which can otherwise feel like the wrong place to look." },
          { image: "assets/tutorials/day1/enlarging-ui-screen-in-sql/step2.jpg", caption: "Windows 10: under Display, drag \"Change the size of text, apps, and other items\" to 125%/150%/200%.", explanation: "Scaling above 100% on Windows 10 can occasionally cause SQL Account dialogs to render with cut-off buttons or misaligned fields, since the app wasn't originally designed for high-DPI scaling — if a customer reports \"buttons are missing\" after enlarging text, this scaling setting is the first thing to check." },
          { image: "assets/tutorials/day1/enlarging-ui-screen-in-sql/step3.jpg", caption: "Windows 7/8/Vista: use the equivalent \"Change the size of all items\" scaling slider under Personalize > Display.", explanation: "This older Control Panel-style scaling slider is functionally the same as the Windows 10 percentage slider seen earlier, just in a different location and UI style — recognizing that Windows 7/8/Vista customers need to be guided to Personalize > Display rather than the Settings app (which doesn't exist on those versions) avoids wasted time giving Windows 10-specific instructions to the wrong OS." },
          { image: "assets/tutorials/day1/enlarging-ui-screen-in-sql/step4.jpg", caption: "Windows XP: Display Properties > Settings > Advanced lets you pick a preset DPI (Normal/Large) or a Custom setting.", explanation: "Windows XP is legacy at this point, but some long-time SQL Account customers still run it on older accounting workstations, so this screen occasionally still comes up in support calls for very established clients." },
          { image: "assets/tutorials/day1/enlarging-ui-screen-in-sql/step5.jpg", caption: "The Custom DPI Setting dialog lets you drag to an exact scale percentage for very fine control.", explanation: "This gives finer control than the fixed Normal/Large presets (e.g. 132% shown here) — useful when a customer needs a specific in-between size rather than jumping straight to 150%, but remind them a restart is usually required for the new DPI to fully apply." },
        ],
      },
    ],
    practiceTask: "Install SQL Account on the training machine, register a new demo company, activate the license, and adjust the UI scale to a comfortable size.",
  },

  2: {
    topic: "Sales & Customer",
    goal: "The new hire can answer the most common customer/payment support questions.",
    lessons: [
      {
        title: "Customer Payment Guide (Local & Multi Currency)",
        steps: [
          { image: "assets/tutorials/day2/customer-payment-guide-local-multi-currency/step1.jpg", caption: "Maintain Customer shows the customer's default currency — this determines whether a payment is same-currency or multi-currency.", explanation: "The Currency field showing \"----\" specifically means the customer is on default local currency (RM), not that no currency was set — a support agent needs to recognize this dash notation, since customers often mistake it for an error or missing configuration." },
          { image: "assets/tutorials/day2/customer-payment-guide-local-multi-currency/step2.jpg", caption: "For a local-currency customer, open Customer Payment Entry, tick the invoice in Knock Off Grid, and confirm the Pay amount.", explanation: "Notice the on-screen reminder that the Paid Amount must also be keyed in RM value when the currency is default — a common data-entry mistake is customers entering the invoice's foreign total here even for a local-currency account, which throws off the knock-off math." },
          { image: "assets/tutorials/day2/customer-payment-guide-local-multi-currency/step3.jpg", caption: "For a foreign-currency invoice paid in local currency, the system auto-calculates the currency rate to knock off the payment.", explanation: "Here the Currency field shows USD with a system Rate of 3.5000 — the Local Amount (3,500.00) is calculated automatically from the Paid Amount, so agents should teach customers not to manually override the Rate unless they specifically need to record a different exchange rate than the system default." },
          { image: "assets/tutorials/day2/customer-payment-guide-local-multi-currency/step4.jpg", caption: "The Local Amount field updates based on the exchange rate at payment date — a forex gain/loss is expected if it differs from the invoice date's rate.", explanation: "This variant shows the customer receiving payment into a foreign-currency bank account (PBB (USD)) rather than a local one, which is why Local Amount becomes an editable blue field instead of a locked calculated one — this distinction (which bank account is selected) is exactly what determines whether Local Amount is auto-locked or user-entered." },
          { image: "assets/tutorials/day2/customer-payment-guide-local-multi-currency/step5.jpg", caption: "For a same-currency foreign payment (e.g. USD invoice paid in USD), select the matching USD bank account so the currency-rate field becomes editable.", explanation: "This example uses an HSBC S$ account to receive a USD-denominated payment — two different currency rates appear (USD rate 3.5042 and S$ @ Rate 2.5030), and the small GainLoss column (here -4.20) is the forex gain/loss automatically posted from the rate difference. Customers frequently ask \"why does my payment show a gain/loss\" — this cross-currency banking scenario is exactly why." },
        ],
      },
      {
        title: "Customer Contra and Supplier Contra",
        steps: [
          { image: "assets/tutorials/day2/customer-contra-and-supplier-contra/step1.jpg", caption: "Before using Contra, confirm Tools > Options > General Ledger has a valid Contra Account configured.", explanation: "If this Contra Account isn't set up first, the Customer Contra and Supplier Contra menu options may error out or fail to post correctly — this is the number one thing to check when a customer says \"Contra isn't working\" before looking at the transaction itself." },
          { image: "assets/tutorials/day2/customer-contra-and-supplier-contra/step2.jpg", caption: "From the Customer menu, choose Customer Contra to start offsetting a sales invoice against a purchase invoice.", explanation: "Customer Contra sits in the same dropdown as Customer Payment and Customer Refund, so it's easy for less experienced staff to overlook — it's specifically for when a business is both a customer and a supplier to the same company and wants to net off what's owed both ways instead of paying/receiving cash." },
          { image: "assets/tutorials/day2/customer-contra-and-supplier-contra/step3.jpg", caption: "Select the customer, enter the Contra Amount, knock off the relevant invoice, and save — the system auto-generates a Contra Number (e.g. CT-00006).", explanation: "Note the auto-generated Contra Number (CT-00006) — this exact same number must be located and matched on the Supplier Contra side for the offset to reconcile correctly, so tell customers to write it down or keep the screen open while doing the second half." },
          { image: "assets/tutorials/day2/customer-contra-and-supplier-contra/step4.jpg", caption: "From the Supplier menu, open Supplier Contra to complete the other half of the offset.", explanation: "This is a separate document type from Customer Contra even though it looks similar — both halves must be entered for the contra to be complete; forgetting the supplier side is a common reason customers see the customer's balance clear but the supplier's balance stay outstanding." },
          { image: "assets/tutorials/day2/customer-contra-and-supplier-contra/step5.jpg", caption: "Locate the same Contra Number, enter a matching Contra Amount, knock off the supplier invoice, and save.", explanation: "The Contra Amount (150.00) and Contra Number (CT-00006) here must exactly match what was entered on the customer side — if the amounts differ, the two ledgers will be out of balance by the difference, which is a frequent \"why doesn't my contra tie out\" support question." },
        ],
      },
      {
        title: "Post-Dated Cheque & Bounced Cheque",
        steps: [
          { image: "assets/tutorials/day2/post-dated-cheque-bounced-cheque/step1.jpg", caption: "Start from Customer > Customer Payment to record the cheque as a normal payment.", explanation: "A post-dated cheque is entered exactly like any other customer payment initially — the special handling only happens afterward via right-click, so there's nothing different to teach customers about the data entry screen itself, only about what happens next." },
          { image: "assets/tutorials/day2/post-dated-cheque-bounced-cheque/step2.jpg", caption: "Right-click near the payment header and choose Set Posting Date to specify the actual future date the cheque clears.", explanation: "This lets the payment be recorded now (with the document date fixed) while the actual GL posting is deferred to when the cheque is expected to clear (16/07/2015 in this example vs the document date of 16/06/2015) — this is exactly what distinguishes a post-dated cheque from a normal payment in SQL Account's ledger." },
          { image: "assets/tutorials/day2/post-dated-cheque-bounced-cheque/step3.jpg", caption: "Review pending post-dated cheques via Customer Post Dated Cheque Listing, filtered by payment date.", explanation: "This report lets staff proactively see which cheques are due to clear on a given date before they actually bank them — a useful screen to point customers to when they ask \"how do I see all the post-dated cheques I'm holding.\"" },
          { image: "assets/tutorials/day2/post-dated-cheque-bounced-cheque/step4.jpg", caption: "To mark a cheque as bounced, right-click near the header on the existing payment and select Bounced Status.", explanation: "This is the same right-click context menu used for Set Posting Date, plus Open Bank Deposit — worth teaching customers that most of the special payment actions in SQL Account live in this one right-click menu, not in a separate module." },
          { image: "assets/tutorials/day2/post-dated-cheque-bounced-cheque/step5.jpg", caption: "The Ledger Report then clearly reflects the reversal on the bounce date, rather than the transaction being deleted.", explanation: "Note the description automatically appends \"(Bounced)\" to the customer name in the ledger — this audit trail is important to point out to customers worried about deleting a bounced cheque entry, since SQL Account is deliberately designed to reverse rather than erase it, preserving the history." },
        ],
      },
      {
        title: "Open Bank Deposit",
        steps: [
          { image: "assets/tutorials/day2/open-bank-deposit/step1.jpg", caption: "Start from Customer > Customer Payment, where individual cheque payments are normally entered.", explanation: "This is the same familiar Customer Payment screen used for every receipt — the Open Bank Deposit feature isn't a separate module a customer needs to find, it's reached via right-click from right here, which is worth stressing since customers often go looking for a distinct \"deposit\" menu that doesn't exist." },
          { image: "assets/tutorials/day2/open-bank-deposit/step2.jpg", caption: "Right-click and choose Open Bank Deposit, then set the deposit date range to search for payments made on that slip.", explanation: "The Maintain Bank Deposit window opens with a blank grid and a Bank Slip No. field — the date range filter at the top is what pulls in candidate payments, so if a customer says \"no data to display\" the first thing to check is whether their date range actually covers the payments they're trying to group." },
          { image: "assets/tutorials/day2/open-bank-deposit/step3.jpg", caption: "Tick all the customer payments that were physically banked together on the same deposit slip, then save.", explanation: "This groups several separate customer receipts (three payments totalling RM21,000 here) under one Bank Slip No., which matters for reconciliation later — the bank statement will show one lump-sum deposit, and this is what lets that single line be matched against multiple internal receipts instead of leaving them all unreconciled." },
          { image: "assets/tutorials/day2/open-bank-deposit/step4.jpg", caption: "At Bank Reconciliation time, set the Bank Statement Date and account, then Apply to bring in transactions to match.", explanation: "This is where the payoff of the earlier grouping step shows up — grouped deposits let one bank statement line reconcile against many underlying receipts at once, saving significant time versus ticking each receipt individually." },
          { image: "assets/tutorials/day2/open-bank-deposit/step5.jpg", caption: "The same Open Bank Deposit option is also reachable from GL > Cash Book Entry by right-clicking near Payment Voucher.", explanation: "This confirms Open Bank Deposit isn't limited to customer receipts — it works the same way for outgoing Payment Vouchers in Cash Book Entry, useful when a customer asks whether they can batch multiple cheque payments (not just receipts) into one bank slip." },
        ],
      },
      {
        title: "Cash Drawer Kick Out",
        steps: [
          { image: "assets/tutorials/day2/cash-drawer-kick-out/step1.jpg", caption: "Under Tools > Options > Barcode, choose Direct Kick Out and select the correct COM Port, then test with the Kick Out button.", explanation: "Direct Kick Out is used when the cash drawer is wired straight into the PC via a serial (COM) port — the Kick Out button here lets the agent test the connection live without needing to ring up a transaction, which is the fastest way to confirm hardware wiring before touching software settings further." },
          { image: "assets/tutorials/day2/cash-drawer-kick-out/step2.jpg", caption: "If the drawer is wired through the receipt printer instead, switch to Printer Kick Out and select the printer from the list.", explanation: "Most modern POS cash drawers are actually triggered through the receipt printer's cash-drawer port rather than a dedicated COM port, so Printer Kick Out is the more commonly needed setting — if a customer's drawer isn't opening, always ask which way it's physically cabled before assuming Direct Kick Out is correct." },
        ],
      },
    ],
    practiceTask: "In the demo company, record a local customer payment, a multi-currency payment, and a bounced cheque reversal.",
  },

  3: {
    topic: "Stock & Inventory",
    goal: "The new hire can troubleshoot everyday stock questions.",
    lessons: [
      {
        title: "Costing Method",
        steps: [
          { image: "assets/tutorials/day3/costing-method/step1.jpg", caption: "Costing Method is set per Stock Group under Maintain Stock Group — choose FIFO, Fixed Costing, or Weighted Average.", explanation: "This is a group-level setting, not a per-item one, which surprises customers who expect to set costing method item-by-item — every stock item inherits its costing method from whichever Stock Group it's assigned to, so changing an item's group can silently change how it's costed." },
          { image: "assets/tutorials/day3/costing-method/step2.jpg", caption: "After changing the method on a group with existing history, run Tools > Analyse Data Integrity so costing reports recalculate correctly from the first transaction date.", explanation: "This utility does far more than just recalculate costing — it also checks AR/AP knock-off integrity, document transfer integrity, and stock transaction reposting, so it's a good general \"fix weird report numbers\" tool to remember, not only for costing method changes." },
        ],
      },
      {
        title: "Barcode",
        steps: [
          { image: "assets/tutorials/day3/barcode/step1.jpg", caption: "Barcode labels are edited in Report Builder, opened from the relevant document's preview screen.", explanation: "This particular preset is labelled \"Barcode (GRN - 35X25) ITEM CODE\" — note that different barcode label templates exist for different document types and sizes, so before troubleshooting a barcode layout issue, confirm the customer is editing the correct template for their actual label stock." },
          { image: "assets/tutorials/day3/barcode/step2.jpg", caption: "Because labels are small, set the report's measurement units to Millimeters under Report > Units so sizing matches the physical label.", explanation: "Report Builder defaults to inches in some installs, which makes fine-tuning a small label (measured in millimeters on the physical roll) much harder — switching units here doesn't change the layout, only how the ruler and size fields are displayed, so it's a safe first step before adjusting anything." },
          { image: "assets/tutorials/day3/barcode/step3.jpg", caption: "In Page Setup, set the custom Paper Size (width/height) to match the physical label dimensions.", explanation: "The Width/Height fields here (35mm x 25mm in this example) must match the customer's actual label roll dimensions exactly — a common complaint of \"my barcodes print cut off or shifted\" almost always traces back to this Page Setup not matching the physical label size." },
          { image: "assets/tutorials/day3/barcode/step4.jpg", caption: "On the barcode object, set Type to Code 128 (the common default) and configure the Bar Width to match the scanner/printer.", explanation: "Code 128 is the default and most broadly compatible symbology, but if a customer's scanner can't read printed labels, mismatched Bar Width (0.012 here) relative to their specific printer's DPI is a frequent culprit — too narrow a bar width on a low-DPI printer produces bars that blur together and become unscannable." },
          { image: "assets/tutorials/day3/barcode/step5.jpg", caption: "An event handler on DetailBeforePrint controls how many labels print per line item — one per unit of quantity.", explanation: "This script (Detail.BandsPerRecord := Document_Detail.GetFieldValue('Qty')) is what makes the label sheet print one barcode per unit rather than just one barcode per invoice line — if a customer wants multiple labels per SKU, this script (not a print-dialog setting) is where that behavior lives." },
        ],
      },
      {
        title: "Stock Adjustment & Stock Take",
        steps: [
          { image: "assets/tutorials/day3/stock-adjustment-stock-take/step1.jpg", caption: "From the Stock menu, choose Print Stock Physical Worksheet to generate the count sheet for warehouse staff.", explanation: "This report lives under Stock > Print Stock Physical Worksheet, right next to Print Stock Reorder Advise — both start from the same menu, so it's worth confirming which specific report a customer means when they say \"the stock report.\"" },
          { image: "assets/tutorials/day3/stock-adjustment-stock-take/step2.jpg", caption: "Filter the worksheet by date/group/location/batch, then click Apply to pull in the current stock list.", explanation: "If the company uses the Location or Batch modules, the on-screen note reminds staff to explicitly group by those fields — skipping this is a common reason a multi-location customer's stock take sheet doesn't separate quantities by warehouse." },
          { image: "assets/tutorials/day3/stock-adjustment-stock-take/step3.jpg", caption: "Preview and print the Stock Take Sheet for staff to fill in actual counted (Physical) quantities by hand.", explanation: "Notice the Book Qty column is pre-filled from the system while Physical Qty is left blank for manual entry — this printed sheet is meant to go out to the warehouse floor on paper, with the Book Qty intentionally shown so staff can spot large unexplained variances as they count, not just to fill in a blank number." },
          { image: "assets/tutorials/day3/stock-adjustment-stock-take/step4.jpg", caption: "Open the Stock Physical Worksheet and Stock Adjustment side by side (Window > Tile Vertical) to compare both screens.", explanation: "Tiling these two windows side by side is the key technique this lesson teaches — it lets staff visually compare book quantity against what was written on the paper count sheet before dragging rows across, rather than retyping every item manually into Stock Adjustment." },
          { image: "assets/tutorials/day3/stock-adjustment-stock-take/step5.jpg", caption: "Select the counted rows and drag-and-drop them into Stock Adjustment — Qty auto-fills as the variance between Physical and Book quantity.", explanation: "The Qty column here is calculated automatically as Physical minus Book (e.g. Book -1,351.00, Physical 2.00 gives an adjustment Qty of 1,351.00) — support agents should know this so they can explain unexpected adjustment quantities to a customer rather than assuming a data entry error." },
        ],
      },
      {
        title: "Maintain Stock Item - Reorder Level & Reorder Qty",
        steps: [
          { image: "assets/tutorials/day3/maintain-stock-item-reorder-level-reorder-qty/step1.jpg", caption: "In Maintain Stock Item, set the Reorder Level (threshold) and Reorder Qty (how much to order when hit).", explanation: "These are two distinct numbers customers often conflate — Reorder Level is the low-stock trigger point (5 units here) while Reorder Qty is how much to order once triggered (30 units), not the target stock level to reach." },
          { image: "assets/tutorials/day3/maintain-stock-item-reorder-level-reorder-qty/step2.jpg", caption: "When balance quantity drops below the reorder level, saving a document triggers a Stock Quantity Control warning dialog.", explanation: "This warning (\"There are Items Below Qty On Hand, Below Reorder Level or Below Min. Qty\") is informational, not a hard block — clicking Yes still lets the document save and go negative or below threshold, so customers asking \"why did it let me sell stock I don't have\" need to understand this is a soft warning, not an enforced stop." },
          { image: "assets/tutorials/day3/maintain-stock-item-reorder-level-reorder-qty/step3.jpg", caption: "Print Stock Reorder Advise generates a report of items below threshold, comparing On Hand Qty against Reorder Level, Min, or Max.", explanation: "The \"Compare to\" dropdown can switch between Reorder Level, Min Qty, or Max Qty — this changes which items surface in the list, so if a customer expects to see an item here and it's missing, check which comparison basis is currently selected." },
          { image: "assets/tutorials/day3/maintain-stock-item-reorder-level-reorder-qty/step4.jpg", caption: "Items can be shift-selected in Reorder Advise and dragged directly into a New Purchase Order, auto-filling the Reorder Qty.", explanation: "This drag-and-drop shortcut saves significant re-typing for purchasing staff — the quantity that lands in the new PO comes straight from each item's configured Reorder Qty, so if the pulled-in quantity looks wrong, the fix is in Maintain Stock Item, not in the PO itself." },
        ],
      },
      {
        title: "Multi Location Module",
        steps: [
          { image: "assets/tutorials/day3/multi-location-module/step1.jpg", caption: "A Purchase Invoice can specify a Location field so goods are received directly into a specific branch/warehouse.", explanation: "The Location column (KL in this example) sits right next to the normal Qty/UOM/Price columns on the Purchase Invoice — it's easy for a customer's data-entry staff to forget to set it, resulting in stock silently landing in the default location instead of the intended branch." },
          { image: "assets/tutorials/day3/multi-location-module/step2.jpg", caption: "The Stock Card report then shows movement split out by that location.", explanation: "Note the Stock Card groups transactions by location as a separate row (\"KL\" shown here) — if a customer says an item's quantity looks wrong at one branch, always check whether they're filtering the Stock Card by the correct Location rather than looking at a company-wide total." },
          { image: "assets/tutorials/day3/multi-location-module/step3.jpg", caption: "For consignment, a Stock Transfer document moves goods from the default warehouse to a customer's consignment location without billing.", explanation: "Stock Transfer has From Location and To Location columns (here moving from the default warehouse to location \"BC\") and does not touch the customer's AR balance — this is the key distinction from an Invoice or Delivery Order, since a transfer is purely an internal stock movement, not a sale." },
          { image: "assets/tutorials/day3/multi-location-module/step4.jpg", caption: "Later, billing only happens for quantity actually sold — the Invoice is issued from the customer's consignment location.", explanation: "The Invoice here specifies Location \"BC\" (the consignment location), and only the quantity actually sold (15 of the transferred 20 units) is billed — this two-step transfer-then-invoice pattern is exactly how consignment stock should be handled, and customers billing everything upfront are doing it wrong." },
          { image: "assets/tutorials/day3/multi-location-module/step5.jpg", caption: "The Stock Card confirms the movement between locations, matching what was transferred and what was billed.", explanation: "With both the BC and KL locations now shown, the Stock Card lets an agent verify the full trail — 20 units transferred in, 15 billed out, leaving 5 remaining at the consignment location — which is the standard way to audit a disputed consignment stock count." },
        ],
      },
      {
        title: "Serial No Module",
        steps: [
          { image: "assets/tutorials/day3/serial-no-module/step1.jpg", caption: "Turn on serial tracking per item: Maintain Stock Item > Edit > tick Serial No.", explanation: "Serial No tracking can only be enabled going forward — ticking this on an item that already has existing stock movements can create data integrity issues, so this is best set up before any transactions are posted for that item, not retrofitted later." },
          { image: "assets/tutorials/day3/serial-no-module/step2.jpg", caption: "Serial numbers can be imported from a Notepad/Word list — one serial number per line.", explanation: "The import expects a strict plain-text format, one serial per line with no extra spacing or headers (as shown in this Notepad file) — a common import failure is a customer pasting from Excel, which can introduce hidden characters or extra columns that break the import." },
          { image: "assets/tutorials/day3/serial-no-module/step3.jpg", caption: "Or entered manually one at a time on the Goods Received Note / Delivery Order.", explanation: "The \"Done\" confirmation dialog shown here is the system's way of confirming the serial numbers were successfully attached to the document — if a customer doesn't see this confirmation, the serials likely weren't saved and the document should be checked before closing it." },
          { image: "assets/tutorials/day3/serial-no-module/step4.jpg", caption: "A confirmation dialog like \"Done\" appears once the serial numbers are successfully applied to the document.", explanation: "This list view (SN00002 through SN00006) shows serials already captured into stock, with Import and Generator links at the bottom for adding more in bulk — the Generator option is worth knowing about for customers who need sequential serials created automatically rather than typed or imported one by one." },
          { image: "assets/tutorials/day3/serial-no-module/step5.jpg", caption: "The Add Serial Number picker lets staff tick specific serials to issue out — mismatches here are the most common serial-number support ticket.", explanation: "Staff must tick the specific physical unit's serial being sold or issued (SN-0004 ticked here among many available) — if the wrong serial is ticked, the stock card will show the correct quantity but the wrong physical unit as sold, which is exactly the kind of mismatch that generates \"my serial number report doesn't match what's in the warehouse\" tickets." },
        ],
      },
    ],
    practiceTask: "Create a stock item with a reorder level, perform a stock adjustment, and print a barcode label.",
  },

  4: {
    topic: "General Ledger & Reports",
    goal: "The new hire can walk a customer through a reconciliation or a report fix.",
    lessons: [
      {
        title: "Bank Reconciliation",
        steps: [
          { image: "assets/tutorials/day4/bank-reconciliation/step1.jpg", caption: "Open GL > Bank Reconciliation, select the Bank Statement Date and account, then click Check Bank Recon.", explanation: "The listing shown here has one bank account (MAYBANK) with a blank Bank Statement Closing, meaning that period hasn't been reconciled yet — always confirm which bank account and which statement date the customer is asking about, since multiple accounts can have completely different reconciliation states." },
          { image: "assets/tutorials/day4/bank-reconciliation/step2.jpg", caption: "GL Bank Reconciliation Listing shows prior reconciliations and whether they're in balance.", explanation: "The Out of Balance column at the far right is the fastest way to spot a problem period at a glance — a non-zero value here means that month's reconciliation was saved without fully tying out, which is worth flagging to the customer even if they didn't ask about that specific period." },
          { image: "assets/tutorials/day4/bank-reconciliation/step3.jpg", caption: "Set the Display Period and useful filters (Show Unticked Transaction, Merge Bank Charges), then click Apply to pull in transactions.", explanation: "Notice the Out of Balance figure here is a large negative number ((2,936.57)) before any ticking has happened — that's expected at this stage since Bank Statement Closing hasn't been entered yet; don't mistake this starting imbalance for an actual accounting error." },
          { image: "assets/tutorials/day4/bank-reconciliation/step4.jpg", caption: "Manually tick each system transaction that matches a line on the physical bank statement, then save.", explanation: "This is a real physical bank statement side by side with the system list — the practical technique is matching each system transaction's amount and date against a line on this statement one by one, which is tedious but the only way to catch discrepancies like a bank charge the customer forgot to record." },
          { image: "assets/tutorials/day4/bank-reconciliation/step5.jpg", caption: "Press F6 (or Preview) to generate the Bank Reconciliation Report — hand this to a customer asking to prove their books match the bank.", explanation: "The report clearly separates \"Cheque(s) not credited by Bank\" from \"Unpresented Cheque(s)\" — understanding this distinction (deposits not yet cleared vs payments not yet cashed) is essential for explaining to auditors or customers why the book balance differs from the bank statement balance on any given date." },
        ],
      },
      {
        title: "Auto Bank Reconciliation",
        steps: [
          { image: "assets/tutorials/day4/auto-bank-reconciliation/step1.jpg", caption: "Same starting point as manual recon: GL > Bank Reconciliation > New, then use Load Statement.", explanation: "The Load Statement button is the entry point to the automated feature — it sits right next to Apply, so it's easy for a customer used to manual reconciliation to overlook it entirely and keep ticking transactions by hand." },
          { image: "assets/tutorials/day4/auto-bank-reconciliation/step2.jpg", caption: "Browse to the actual bank statement file exported from online banking (PDF or CSV).", explanation: "The file must be the actual export downloaded from the bank's online portal (PDF or CSV) — a scanned image or manually retyped statement will not work, since the auto-match feature parses the file's text/structure directly." },
          { image: "assets/tutorials/day4/auto-bank-reconciliation/step3.jpg", caption: "The system detects the bank name from the file and asks for confirmation before proceeding.", explanation: "This confirmation exists because SQL Account supports statement formats from multiple named banks (Maybank shown here) — if this detection guesses the wrong bank, the parsing will likely fail or misread columns, so answering \"No\" and checking the file/bank selection is the right move rather than forcing it through." },
          { image: "assets/tutorials/day4/auto-bank-reconciliation/step4.jpg", caption: "Matched transactions get auto-ticked based on cheque number + amount or description + amount.", explanation: "The right-hand \"Bank Statement (Match)\" column shows the matched statement description next to each GL transaction, and matched rows are pre-ticked — this side-by-side view is the quickest way to explain to a customer why a particular transaction did or didn't auto-match." },
          { image: "assets/tutorials/day4/auto-bank-reconciliation/step5.jpg", caption: "Transactions that can't be auto-matched are flagged — click the unmatched line and search by same DR/CR amount to match manually.", explanation: "Auto-matching relies on cheque number or description text lining up exactly with the amount — small differences (like a bank abbreviating a payee name differently than the GL description) will cause a transaction to fall through to manual matching, so this isn't a sign of an error, just a matching-algorithm limitation." },
        ],
      },
      {
        title: "Trial Balance not Tally",
        steps: [
          { image: "assets/tutorials/day4/trial-balance-not-tally/step1.jpg", caption: "First check: GL > Maintain Chart of Account — Retained Earnings must have exactly one account code assigned.", explanation: "If two account codes are both flagged as Retained Earning (or none are), the system can't correctly roll forward prior year profit, which shows up as a trial balance that won't tally — this is the very first thing to check before digging into individual transactions, since it's a setup issue, not a data issue." },
          { image: "assets/tutorials/day4/trial-balance-not-tally/step2.jpg", caption: "Second check: GL > Maintain Opening Balance — untick Project and confirm total Local DR equals Local CR at the bottom.", explanation: "The bottom totals here (29,775,267.95 on both DR and CR) must match exactly — if a customer's opening balance was entered with even a small DR/CR mismatch, every subsequent trial balance will carry that same imbalance forward no matter how correct later transactions are, so this screen is the second must-check after Retained Earnings." },
        ],
      },
      {
        title: "Guide to Calculate Profit & Loss Percentage",
        steps: [
          { image: "assets/tutorials/day4/guide-to-calculate-profit-loss-percentage/step1.jpg", caption: "Every P&L percentage column (Sales %, Gross Profit %, etc.) uses the same formula: (Account Amount ÷ Total Sales) × 100.", explanation: "Total Sales here is 296,502.11 (100.0%), and every other percentage on the report — like Sales-Accessories at 184,119.49 showing 62.1% — is simply that account's amount divided by this one total sales figure. Customers who ask \"why is my gross profit % higher than 100\" usually have a data issue in Total Sales itself, not a formula bug, since every percentage is anchored to that one denominator." },
          { image: "assets/tutorials/day4/guide-to-calculate-profit-loss-percentage/step2.jpg", caption: "The same formula continues down through Expenses % and Net Profit % — percentages round to 1 decimal place by default, explaining small rounding differences customers notice.", explanation: "Because every line rounds independently to one decimal place, the percentages down the report won't always sum to exactly 100.0% or exactly match a hand-calculated figure — this rounding behavior, not a calculation error, is almost always the explanation when a customer says \"the percentages don't quite add up.\"" },
        ],
      },
      {
        title: "Fast Report - Basic Guide",
        steps: [
          { image: "assets/tutorials/day4/fast-report-basic-guide/step1.jpg", caption: "A report layout in Report Designer is built from bands — Group Header/Footer, Master Data, Detail Data, and Page Footer.", explanation: "Understanding this band structure is essential before touching any custom report — content placed in the wrong band (e.g. putting a total in Detail Data instead of Group Footer) will repeat once per line item instead of appearing once, which is a very common \"my custom report prints the total multiple times\" issue." },
          { image: "assets/tutorials/day4/fast-report-basic-guide/step2.jpg", caption: "Use the alignment tools to align objects: click the first object as the anchor, then Shift-click the rest to line them up.", explanation: "The first object clicked becomes the fixed anchor point that all subsequently shift-clicked objects align to — getting the click order backwards is why customers sometimes complain that using the align buttons \"moved the wrong thing\" instead of lining fields up as expected." },
          { image: "assets/tutorials/day4/fast-report-basic-guide/step3.jpg", caption: "An Overlay region can be added over a band to control layered content like watermarks or stamps.", explanation: "An Overlay region sits visually on top of other content in the same area (like the blank green-outlined \"Overlay1\" box shown here) — this is the mechanism used for things like a \"CANCELLED\" or \"DUPLICATE\" stamp that needs to render over existing invoice content rather than push it aside." },
          { image: "assets/tutorials/day4/fast-report-basic-guide/step4.jpg", caption: "The Expression Editor lets you build conditional filters (e.g. filtering leave types) using available datasets and fields.", explanation: "This example expression (LeaveType = 'AL' OR LeaveType = 'MC') shows the Expression Editor being used to filter a payroll leave dataset — the same tool and syntax applies to any dataset in the system, so this is a transferable skill for building conditional logic into many different custom reports, not just leave reports." },
          { image: "assets/tutorials/day4/fast-report-basic-guide/step5.jpg", caption: "Toggle \"Allow Expressions\" on a field's edit menu to enable script-driven formatting on that object.", explanation: "This checkbox must be ticked before a field will respect any script-based formatting or conditional logic applied to it — if a customer writes a seemingly correct OnGetText script but the field still shows raw data, this setting being off is the most common reason." },
        ],
      },
      {
        title: "RTM Report: How to Change 6% to 0%",
        steps: [
          { image: "assets/tutorials/day4/rtm-report-how-to-change-6-to-0/step1.jpg", caption: "A standard sales invoice report correctly shows GST Amt @ 6% based on the invoice date.", explanation: "This invoice is dated before Malaysia's GST rate change, so it correctly displays \"GST Amt @ 6%\" — the report is reading the invoice's TaxDate to decide which label to print, not a fixed setting, which is the key mechanic this whole lesson explains." },
          { image: "assets/tutorials/day4/rtm-report-how-to-change-6-to-0/step2.jpg", caption: "The underlying script (lbTaxAmtOnGetText) compares the invoice's TaxDate against the GST cutover date to decide 6% vs 0% text.", explanation: "The hardcoded cutover date '01 Jun 2018' inside this script is exactly what determines the 6%-vs-0% switch — this is Malaysia's actual GST-to-SST transition date, and any custom report that was cloned before this script existed will keep showing 6% regardless of invoice date until this logic is manually added." },
          { image: "assets/tutorials/day4/rtm-report-how-to-change-6-to-0/step3.jpg", caption: "After the cutover, the same report correctly displays GST Amt @ 0% for a later invoice date.", explanation: "Same invoice layout, later date — this confirms the script is working correctly by showing the expected \"GST Amt @ 0%\" output, which is the exact before/after comparison to show a customer who's confused about why two similar-looking invoices display different tax labels." },
          { image: "assets/tutorials/day4/rtm-report-how-to-change-6-to-0/step4.jpg", caption: "On a customized report, this logic must be manually re-applied via View > Events in Report Designer.", explanation: "Any report a customer has customized or cloned from an older template will not automatically inherit this date-comparison logic — it must be manually added into the report's Events, which is exactly why some customers see the standard invoice behave correctly while their customized version still shows the wrong rate." },
          { image: "assets/tutorials/day4/rtm-report-how-to-change-6-to-0/step5.jpg", caption: "A related fix: an OnGetText script (DBTxtTaxOnGetText) that forces a blank tax amount to display as '0.00' instead of blank.", explanation: "Without this script, a zero-rated invoice's tax amount field can render as a confusing blank space instead of \"0.00\" — this is a small but frequently-requested cosmetic fix, since customers often assume a blank tax field means the report is broken rather than correctly showing zero." },
        ],
      },
      {
        title: "How to do Rounding Report",
        steps: [
          { image: "assets/tutorials/day4/how-to-do-rounding-report/step1.jpg", caption: "An invoice with a hidden line item code (e.g. RTN5Cents) captures the cash-rounding adjustment separately from normal items.", explanation: "The RTN5Cents line (0.02 here) is a real invoice line item, just one meant to stay hidden from the printed copy — this trick of using a genuine but suppressed stock code is the core technique behind Malaysia's 5-cent cash rounding requirement on printed receipts." },
          { image: "assets/tutorials/day4/how-to-do-rounding-report/step2.jpg", caption: "In Report Designer, a custom SQL query bound in the Calc module (run onCreate/onBeforePrint) pulls in the rounding amount.", explanation: "A dedicated variable (SQL_Rounding) is declared specifically to hold this rounding query's result — this is a good pattern to recognize when reviewing a customer's customized report script, since it shows a separate query was deliberately added on top of the standard invoice dataset." },
          { image: "assets/tutorials/day4/how-to-do-rounding-report/step3.jpg", caption: "The report preview shows the invoice total rounded cleanly, with the rounding line summed separately.", explanation: "The rounding amount (0.02, boxed here) is broken out as its own labeled figure on the printed invoice rather than silently folded into the subtotal — this transparency is often a compliance requirement, so if a customer's printed rounding amount doesn't match their sales tax report, check whether this figure is being captured consistently." },
          { image: "assets/tutorials/day4/how-to-do-rounding-report/step4.jpg", caption: "The rounding item's detail region is set to No Fill / hidden so it doesn't clutter the printed item list.", explanation: "No Fill here controls the region's background appearance, but the actual line-hiding logic is a separate OnPrint event (covered in the next step) — No Fill alone doesn't hide the row, it just removes any distracting background color/border from it." },
          { image: "assets/tutorials/day4/how-to-do-rounding-report/step5.jpg", caption: "An OnPrint event on the region controls visibility — hiding the rounding code (RTN5Cents) from the visible printed list.", explanation: "This script (RDisc.Visible := Document_Detail.getfieldvalue('Itemcode') <> 'RTN5Cents') is what actually suppresses the RTN5Cents and DISC lines from appearing in the printed item list, while still letting their values feed into the totals — this is the key script to check if a customer's rounding item is showing up visibly on their printed invoices when it shouldn't." },
        ],
      },
    ],
    practiceTask: "Run a bank reconciliation on demo data, generate a P&L statement, and apply one Fast Report fix from the guide.",
  },

  5: {
    topic: "Tools, Troubleshooting & Review",
    goal: "The new hire can handle access requests and basic database issues, and consolidates the whole week.",
    lessons: [
      {
        title: "Create A New User, Access Control & Reset Password",
        steps: [
          { image: "assets/tutorials/day5/create-a-new-user-access-control-reset-password/step1.jpg", caption: "Under Tools, open Maintain User to create or manage users.", explanation: "Maintain User sits under Tools alongside Maintain User Group and User Access Right Assignment — worth knowing all three exist together, since customers sometimes describe wanting one of the other two when they actually ask for \"Maintain User.\"" },
          { image: "assets/tutorials/day5/create-a-new-user-access-control-reset-password/step2.jpg", caption: "In the User screen, use the More button to reach Access Control, Reset Password, and other options.", explanation: "The More dropdown is where most of the powerful user-management actions live (Access Control, Export/Import Access Right, Reset Password, Document Number, Form Mode) — it's easy for a new agent to miss this button since it looks like a secondary action rather than the main menu of user features." },
          { image: "assets/tutorials/day5/create-a-new-user-access-control-reset-password/step3.jpg", caption: "Reset Password generates a temporary password that can be copied to clipboard for the user.", explanation: "The system generates a random temporary password (e.g. wJOxbuCN) rather than letting the admin type one — the \"Copy password to clipboard\" checkbox is ticked by default, so remind the agent to actually paste and record it somewhere immediately, since this dialog won't show the password again once closed." },
          { image: "assets/tutorials/day5/create-a-new-user-access-control-reset-password/step4.jpg", caption: "The user logs on with the temporary password on the SQL Account login screen.", explanation: "This is the standard login screen where the temporary password gets used — the eye icon lets the user reveal what they're typing, which is worth pointing out to customers who struggle to type a random password correctly on the first attempt." },
          { image: "assets/tutorials/day5/create-a-new-user-access-control-reset-password/step5.jpg", caption: "They're then prompted to set a new permanent password on first login, confirming the change succeeded.", explanation: "The \"User [ACC] password changed\" confirmation is the system's proof the reset flow completed correctly — if a customer says a reset password \"didn't work,\" ask specifically whether they saw this exact confirmation dialog, since its absence usually means the new password didn't actually save." },
        ],
      },
      {
        title: "Password Policy (with 2 steps Verification)",
        steps: [
          { image: "assets/tutorials/day5/password-policy-with-2-steps-verification/step1.jpg", caption: "Company-wide rules live under Tools > Options > Password Policy — Maximum Password Age, Minimum Length, Password History, and required character mix.", explanation: "These are company-wide rules that apply to every user, not settings configured per individual — a customer confused about why their new password keeps getting rejected should be pointed here first, since the actual requirements (minimum length, character mix, password history) are fully visible and adjustable on this one screen." },
          { image: "assets/tutorials/day5/password-policy-with-2-steps-verification/step2.jpg", caption: "New-user resets use the same More > Reset Password flow as standard password resets.", explanation: "This confirms Reset Password is the same unified flow regardless of whether Password Policy is active — the policy rules (minimum length, character mix, etc.) are enforced on top of this same screen, not through a separate mechanism." },
          { image: "assets/tutorials/day5/password-policy-with-2-steps-verification/step3.jpg", caption: "Two-Step Verification is enabled per user under File > 2-Steps Verification, starting with the current password.", explanation: "Requiring the current password before enabling 2-Step Verification is a security measure to stop someone else from turning it on for a user's account without their knowledge — if a customer forgot their current password, they'll need a password reset first before they can even attempt to enable 2-Step Verification." },
          { image: "assets/tutorials/day5/password-policy-with-2-steps-verification/step4.jpg", caption: "The user then links an authenticator app on their phone (iPhone, Android, or Windows Phone).", explanation: "This is a standard TOTP (time-based one-time password) authenticator setup, compatible with apps like Google Authenticator — if a customer changes phones later, they'll need to redo this linking step, since the authenticator secret isn't automatically transferred." },
          { image: "assets/tutorials/day5/password-policy-with-2-steps-verification/step5.jpg", caption: "After that, every login requires a time-based verification code from the authenticator app.", explanation: "This verification code prompt now appears on every login for that user going forward — the most common support ticket related to this feature is a customer who lost or reset their phone and can no longer generate codes, which typically requires an admin to disable 2-Step Verification for that user from another account with sufficient rights." },
        ],
      },
      {
        title: "Maintain User",
        steps: [
          { image: "assets/tutorials/day5/maintain-user/step1.jpg", caption: "Full user setup lives under Tools > Maintain User in the main menu.", explanation: "This lesson revisits the same Maintain User screen from earlier in the week but goes deeper into Access Control and rights import/export — worth telling new hires this is intentional repetition, since user/access management is one of the most frequent support request categories and is worth over-learning." },
          { image: "assets/tutorials/day5/maintain-user/step2.jpg", caption: "Create the user with New, assign a Code/Name, and Save; passwords are set via More > Change Password.", explanation: "Note every new user automatically belongs to the ADMINISTRATORS group by default until explicitly reassigned — if a customer wants a restricted new user, remind them this default group membership needs to be changed, not just left as-is, or the new user will start with full access rather than limited rights." },
          { image: "assets/tutorials/day5/maintain-user/step3.jpg", caption: "Access Control uses a four-tier permission model per module — Execute, New, Edit, and Delete — plus Grant/Revoke actions to apply them.", explanation: "This reference table is worth memorizing: Execute simply lets a user open/use a function, while New/Edit/Delete separately control creating, modifying, and removing documents — a user can, for example, have Execute+New but not Edit, letting them raise new invoices without being able to alter existing ones. The Process permission is specifically noted as not applicable to SQL Accounting (only SQL Payroll uses it), a detail worth remembering when a customer asks about a grayed-out Process option." },
          { image: "assets/tutorials/day5/maintain-user/step4.jpg", caption: "Export Access Right saves an existing user's permissions to an XML file.", explanation: "This exports one user's complete permission set as an XML file — the practical use case is setting up a \"template\" user with the exact rights a role needs, then exporting it so those same rights can be applied to other staff without manually reconfiguring every module's Execute/New/Edit/Delete flags." },
          { image: "assets/tutorials/day5/maintain-user/step5.jpg", caption: "Import Access Rights on a new user then copies those permissions over instead of re-configuring from scratch — confirm the overwrite warning to proceed.", explanation: "This warning makes clear that importing completely overwrites the target user's existing access rights rather than merging with them — always double-check with the customer that this is really what they want before confirming Yes, since there's no automatic way to see the old permissions again afterward." },
        ],
      },
      {
        title: "Fix Database Shutdown Error",
        steps: [
          { image: "assets/tutorials/day5/fix-database-shutdown-error/step1.jpg", caption: "Launch SQL Diagnosis V2 and click Database Online — this is the dedicated tool for a database stuck showing a shutdown error.", explanation: "A \"database shutdown\" error typically happens after an abnormal disconnect (power loss, forced restart, network drop) leaves the Firebird database flagged offline — SQL Diagnosis V2's Database Online tool is specifically built to clear that flag, and the on-screen warning to back up first should always be followed since this tool works directly against the live database file." },
          { image: "assets/tutorials/day5/fix-database-shutdown-error/step2.jpg", caption: "Select the affected database file and run it — \"Database Back Online\" confirms the shutdown state was cleared.", explanation: "The \"Database Back Online\" confirmation message is the definitive sign the fix worked — if a customer still can't log in after seeing this message, the underlying problem is likely something else entirely (network, credentials, corrupt data) rather than the shutdown state, and troubleshooting should move on from this specific tool." },
        ],
      },
      {
        title: "How to validate database with SQL Diagnosis Utility",
        steps: [
          { image: "assets/tutorials/day5/how-to-validate-database-with-sql-diagnosis-utility/step1.jpg", caption: "Open SQL Accounting Diagnosis and click Database Validate.", explanation: "Note this diagnosis tool also has Database Clone, Database Patch, and External Batch Backup right alongside Database Validate — worth knowing these other tools exist in the same toolbar for related database-health tickets." },
          { image: "assets/tutorials/day5/how-to-validate-database-with-sql-diagnosis-utility/step2.jpg", caption: "Choose the Firebird version matching the customer's setup (commonly Firebird 2.5).", explanation: "Selecting the wrong Firebird version here can cause the validation to fail or behave unexpectedly even on a perfectly healthy database — if unsure which version the customer runs, check their Firebird install or the version noted in the main SQL Account status bar before running Validate." },
          { image: "assets/tutorials/day5/how-to-validate-database-with-sql-diagnosis-utility/step3.jpg", caption: "Browse the SQL Financial Accounting Database screen to confirm the exact .FDB file location being validated.", explanation: "Always confirm the exact .FDB filename and path shown here (ACC-0160.FDB in this example) matches the database the customer is actually having trouble with — on a server with multiple company databases it's easy to accidentally validate the wrong file." },
          { image: "assets/tutorials/day5/how-to-validate-database-with-sql-diagnosis-utility/step4.jpg", caption: "Click Validate, then Backup — \"Database Validation Complete\" confirms a clean check; a \"bad parameter\" error means escalate to the SQL helpdesk.", explanation: "\"Database Validation Complete\" with no errors listed in the log area means the database is structurally healthy — but a \"bad parameter\" or similar low-level error here indicates real corruption that's beyond front-line troubleshooting and should be escalated with the backup file attached, not repeatedly re-run." },
          { image: "assets/tutorials/day5/how-to-validate-database-with-sql-diagnosis-utility/step5.jpg", caption: "After a successful backup+restore, the old and new copies sit side by side — use Drop Database Link (recoverable) rather than Delete Database (permanent) when cleaning up.", explanation: "This distinction is critical and easy to get backwards under pressure: Drop Database Link only removes the shortcut/reference from this list (the underlying .FDB file is untouched and can be re-added later), while Delete Database permanently destroys the actual file — always guide customers toward Drop Database Link when they just want to tidy up the list." },
        ],
      },
      {
        title: "SQL Backup Database & Restore Database",
        steps: [
          { image: "assets/tutorials/day5/sql-backup-database-restore-database/step1.jpg", caption: "From the main menu, go to File > Backup Database to start a backup.", explanation: "This is the same File menu used throughout the week for Company Profile, Product Activation, and Logon — worth reinforcing to new hires that this one menu is the hub for nearly every company-level housekeeping action in SQL Account, not just document entry." },
          { image: "assets/tutorials/day5/sql-backup-database-restore-database/step2.jpg", caption: "Use the Restore link under Housekeeping to restore from a backup file.", explanation: "Restore sits directly under Backup in the same Housekeeping section — note there's also a cloud-icon \"Restore...\" option beneath the standard one for cloud-based backups, so confirm with the customer whether they're restoring from a local file or a cloud backup before picking the wrong link." },
          { image: "assets/tutorials/day5/sql-backup-database-restore-database/step3.jpg", caption: "Restoring creates a separate company entry in the database list rather than overwriting the original.", explanation: "This is an important safety behavior to explain to nervous customers: restoring a backup does not overwrite their existing live company data, it creates an additional separate entry in the database list — so restoring \"just to check\" a backup is safe and won't risk their current data." },
          { image: "assets/tutorials/day5/sql-backup-database-restore-database/step4.jpg", caption: "When backing up, toggle Compress Backup File (and Best Compression Mode for a smaller file at the cost of speed), then click Backup.", explanation: "Best Compression Mode produces a smaller backup file but takes noticeably longer to complete — for a large database, recommend leaving Best Compression Mode off for routine daily backups and only using it when file size (e.g. for emailing a backup) genuinely matters." },
          { image: "assets/tutorials/day5/sql-backup-database-restore-database/step5.jpg", caption: "The new backed-up/restored company now appears alongside the original in the database list, ready to compare or switch to.", explanation: "This final list view is the practical proof point to show a customer worried about data loss — both the original and the newly backed-up/restored copy are visible side by side, confirming nothing was overwritten during the process." },
        ],
      },
    ],
    practiceTask: "Create a new user with limited access rights, run the SQL Diagnosis Utility to validate a database, and perform a full backup + restore cycle.",
  },
};
